### ISSUE TITLE
"undefined vundefined successfully initialized!"

### ISSUE THREAD

**Issue by dylanh724** [KockaAdmiralac/WikiaActivityLogger#30]
Very strange welcome message :)

**Comment by KockaAdmiralac** [comment]
Oh yeah, that's because the new version of npm appanrently doesn't expose `process.env.npm_*` variables so I'll have to load package.json from the places that used these variables. It's in my todo list for WikiaActivityLogger and I'll eventually get to fixing it (unless, of course, you want to make a pull request to fix it)

**Comment by dylanh724** [comment]
Sorry haha I would have -- I only just got enough time recently!
