### ISSUE TITLE
Allow updates to be posted as embeds

### ISSUE THREAD

**Issue by ClementJ18** [KockaAdmiralac/WikiaActivityLogger#37]
Would it be possible to make it so that, as an option, users could choose that the updated be posted as an embed? 
It should only require a valid embed object and an additional parameter in the POST request and would allow users to customize the messages further.

**Comment by KockaAdmiralac** [comment]
How would you want the embed to look like? If you just want the content posted through an embed with whatever color to the left, that's easy to do but not very useful because it would clutter logging channels more. If you need it to contain additional information, like user's avatar/username in embed fields, that would require a complete overhaul of how i18n is being formatted and how log messages are being passed to transports.

**Comment by KockaAdmiralac** [comment]
See #43.
